### ISSUE TITLE
Todo list filter by tag

### ISSUE THREAD

**Issue by Kardelio** [Kardelio/todo#1]
Currently you can do:

todo -l 9

to filter and just look at list 9
OR

todo -p 1

to filter and just look at priority items 1

I would like to filter by tag strings

so :

todo -t THURS

for example...

**Comment by HurrieCrane** [comment]
I'll do this one plz

**Comment by Kardelio** [comment]
@HurrieCrane do it, you wont...

**Comment by Kardelio** [comment]
@HurrieCrane zzzzz 😴

**Comment by Kardelio** [comment]
@HurrieCrane shall I un-assign this good sir?
🙃

**Comment by gabekz** [comment]
If you'll take a PR, I'd like to contribute.

**Comment by Kardelio** [comment]
@GabeKutuzov hell yes, why not! Get stuck in :) does the ticket itself make sense? I know the documentation on this repo aint tip top, so please let me know if not, but would love for you to contribute :)

**Comment by gabekz** [comment]
> @GabeKutuzov hell yes, why not! Get stuck in :) does the ticket itself make sense? I know the documentation on this repo aint tip top, so please let me know if not, but would love for you to contribute :)

Perfect! I will have time between Christmas and the New Year to try and tackle this little beast. Looking forward to it!

**Comment by Kardelio** [comment]
@GabeKutuzov awesome! Look forward to seeing the results! No rush at all 😄

**Comment by Kardelio** [comment]
Hey @GabeKutuzov just wondering if you have had the time to look into this yet? If not dont worry just following up

**Comment by Kardelio** [comment]
Done in Commit: 7b788f6e400d14695f97ff5004f217e3094263df
